all: AdminController.class CustomerController.class

AdminController.class: AdminController.java
	javac -d ./../../../out -classpath ./../../../out AdminController.java
CustomerController.class: CustomerController.java
	javac -d ./../../../out -classpath ./../../../out CustomerController.java