all: CommonMarketplace.class MarketplaceView.class

CommonMarketplace.class: CommonMarketplace.java
	javac -d ./../../../out -classpath ./../../../out CommonMarketplace.java
MarketplaceView.class: MarketplaceView.java
	javac -d ./../../../out -classpath ./../../../out MarketplaceView.java
