all: Dispatcher.class FrontController.class

Dispatcher.class: Dispatcher.java
	javac -d ./../../../out -classpath ./../../../out Dispatcher.java
FrontController.class: FrontController.java
	javac -d ./../../../out -classpath ./../../../out FrontController.java