all: Marketplace.class AdminMarketplace.class CustomerMarketplace.class MarketplaceImpl.class AdminMarketplaceImpl.class CustomerMarketplaceImpl.class MarketplaceServer.class

Marketplace.class: Marketplace.java
	javac -d ./../../../out -classpath ./../../../out Marketplace.java
AdminMarketplace.class: AdminMarketplace.java
	javac -d ./../../../out -classpath ./../../../out AdminMarketplace.java
CustomerMarketplace.class: CustomerMarketplace.java
	javac -d ./../../../out -classpath ./../../../out CustomerMarketplace.java
MarketplaceImpl.class: MarketplaceImpl.java
	javac -d ./../../../out -classpath ./../../../out MarketplaceImpl.java
AdminMarketplaceImpl.class: AdminMarketplaceImpl.java
	javac -d ./../../../out -classpath ./../../../out AdminMarketplaceImpl.java
CustomerMarketplaceImpl.class: CustomerMarketplaceImpl.java
	javac -d ./../../../out -classpath ./../../../out CustomerMarketplaceImpl.java
MarketplaceServer.class: MarketplaceServer.java
	javac -d ./../../../out -classpath ./../../../out MarketplaceServer.java
