all: UserDTO.class ProductDTO.class CartDTO.class AdminDTO.class CustomerDTO.class
UserDTO.class: UserDTO.java
	javac -d ./../../../../out -classpath ./../../../../out UserDTO.java
ProductDTO.class: ProductDTO.java
	javac -d ./../../../../out -classpath ./../../../../out ProductDTO.java
CartDTO.class: CartDTO.java
	javac -d ./../../../../out -classpath ./../../../../out CartDTO.java
AdminDTO.class: AdminDTO.java
	javac -d ./../../../../out -classpath ./../../../../out AdminDTO.java
CustomerDTO.class: CustomerDTO.java
	javac -d ./../../../../out -classpath ./../../../../out CustomerDTO.java
