all: LandPage.class LandPageBuilding.class UserLandPageFactory.class AdminLandPage.class CustomerLandPage.class AdminLandPageFactory.class CustomerLandPageFactory.class  UserLandPageBuilding.class

LandPage.class: LandPage.java
	javac -d ./../../../out -classpath ./../../../out LandPage.java
LandPageBuilding.class: LandPageBuilding.java
	javac -d ./../../../out -classpath ./../../../out LandPageBuilding.java
UserLandPageFactory.class: UserLandPageFactory.java
	javac -d ./../../../out -classpath ./../../../out UserLandPageFactory.java
AdminLandPage.class: AdminLandPage.java
	javac -d ./../../../out -classpath ./../../../out AdminLandPage.java
CustomerLandPage.class: CustomerLandPage.java
	javac -d ./../../../out -classpath ./../../../out CustomerLandPage.java
AdminLandPageFactory.class: AdminLandPageFactory.java
	javac -d ./../../../out -classpath ./../../../out AdminLandPageFactory.java
CustomerLandPageFactory.class: CustomerLandPageFactory.java
	javac -d ./../../../out -classpath ./../../../out CustomerLandPageFactory.java
UserLandPageBuilding.class: UserLandPageBuilding.java
	javac -d ./../../../out -classpath ./../../../out UserLandPageBuilding.java
