all: AdminMenu.class CustomerMenu.class

AdminMenu.class: AdminMenu.java
	javac -d ./../../../out -classpath ./../../../out AdminMenu.java
CustomerMenu.class: CustomerMenu.java
	javac -d ./../../../out -classpath ./../../../out CustomerMenu.java
