all: AuthorizationException.class RequiresRole.class Session.class AuthorizationInvocationHandler.class

AuthorizationException.class: AuthorizationException.java
	javac -d ./../../../out -classpath ./../../../out AuthorizationException.java
RequiresRole.class: RequiresRole.java
	javac -d ./../../../out -classpath ./../../../out RequiresRole.java
Session.class: Session.java
	javac -d ./../../../out -classpath ./../../../out Session.java
AuthorizationInvocationHandler.class: AuthorizationInvocationHandler.java
	javac -d ./../../../out -classpath ./../../../out AuthorizationInvocationHandler.java
