all: Controller.class BaseController.class

Controller.class: Controller.java
	javac -d ./../../../out -classpath ./../../../out Controller.java
BaseController.class: BaseController.java
	javac -d ./../../../out -classpath ./../../../out BaseController.java