all: Command.class Login.class UserRequest.class

Command.class: Command.java
	javac -d ./../../../out -classpath ./../../../out Command.java
Login.class: Login.java
	javac -d ./../../../out -classpath ./../../../out Login.java
UserRequest.class: UserRequest.java
	javac -d ./../../../out -classpath ./../../../out UserRequest.java